### PR TITLE
Feature/update 7.10.1

### PR DESCRIPTION
**Pull request by ch-bas**
* Update to the new Kibana's Platform.
* Adapt the readme file.
* Update the plugin's screenshot.

### CODE REVIEW

**Comment by bfgiordano** [comment]
We were able to load and successfully visualize the data on the Sankey on an ES/K 7.10.1 instance.. We used the version from Develop that was available Friday morning (2/19/21).

One question - I thought in one of the previous releases that the ability to Inspect the data behind the visualization had been added? I did not see any data for the Sankey when I selected Inspect-> View:Data. Just wondering if I am mistaken and that capability was never available in 7.6.x plugin or if it was lost in the migration to support for 7.10 plugin.

**Comment by ch-bas** [comment]
@bfgiordano , thanks for reporting this! 
I presume this feature was lost during the upgrade to the new Kibana's platform.
I will try to debug it soon.
Thanks!

**Comment by bfgiordano** [comment]
Thank you very much!

**Comment by ch-bas** [comment]
@bfgiordano , you should be able now to see the data when you use the inspect view.

**Comment by bfgiordano** [comment]
Wil check it out - thank you!

**Pull request merged**
